---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - args:
          - --maxkb=2000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
      - id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest

        files: \.[jt]s?$
        id: eslint
        types:
          - file
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.37.0
  - hooks:
      - id: prettier
        additional_dependencies:
          - "prettier-plugin-svelte"
        types_or:
          [
            css,
            javascript,
            jsx,
            tsx,
            ts,
            html,
            markdown,
            scss,
            yaml,
            gitignore,
            toml,
          ]
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
