---
name: Client

on:
  workflow_dispatch:
  push:
    paths:
      - "client/**"
      - ".github/workflows/client.yml"
  pull_request:

jobs:
  client:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: client/pnpm-lock.yaml
      - name: Install deps and run test
        run: |
          cd client
          pnpm install
          # npm test
          npm run build
      - name: Publish to Cloudflare
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "2af0b6ae38d7dc64d9cef389245cf5fa"
          projectName: optom-resources-client
          directory: client/.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
