---
name: CMS

on:
  workflow_dispatch:
  push:
    paths:
      - "cms/**"
      - ".github/workflows/cms.yml"
  pull_request:
    paths:
      - "cms/**"
      - ".github/workflows/cms.yml"

jobs:
  cms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: cms/pnpm-lock.yaml
      - name: Install deps and run test
        run: |
          cd cms
          pnpm install
          npm run build
      - name: Publish to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "2af0b6ae38d7dc64d9cef389245cf5fa"
          projectName: optom-resources-cms
          directory: cms/dist
