---
name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ["cms", "client"]
    name: ${{ matrix.app }} CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: ${{ matrix.app }}/pnpm-lock.yaml

      - name: Install deps
        run: >
          cd ${{ matrix.app }} && \
          pnpm install
